before_install:
  - "echo '--colour' > ~/.rspec"
  - "echo 'gem: --no-document' > ~/.gemrc"
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install:
  - bin/setup
branches:
  only:
    - master
cache:
  - bundler
language:
  - ruby
notifications:
  email:
    - false
rvm:
  - 2.1.5
addons:
  postgresql: "9.3"
  code_climate:
    repo_token:
      secure: "bF99D9E+F8GgEGyraMJX/2pqzm8DDpRa0y+s73gWHRdSu18/k1QLsxEIL8FfeFYtc0E2GVbXlbPOtYmNcZP9dZrGWf94ztLxtTh9KcO5LdGDd+Vp6WyEdufamdCCXXPLzh/pxGWG6cRkn9hXMdZzTeaDEcPjDn03MPOiz5wgJ28="
