default: &default
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

development:
  forest_env_secret: b0647f23e4f4a5d3b4568498bdd2d39721e30968ff87dfcf5d0199d047609549
  forest_auth_secret: oXC3pl0z9cIhZWWk5QeT5w
  <<: *default

test:
  <<: *default

staging:
  forest_env_secret: <%= ENV["FOREST_ENV_SECRET"] %>
  forest_auth_secret: <%= ENV["FOREST_AUTH_SECRET"] %>
  <<: *default

production:
  forest_env_secret: <%= ENV["FOREST_ENV_SECRET"] %>
  forest_auth_secret: <%= ENV["FOREST_AUTH_SECRET"] %>
  <<: *default
